apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j32nszn8l-go
  janus-idp.io/tekton: j32nszn8l-go
  backstage.io/kubernetes-id: j32nszn8l-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j32nszn8l-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
